// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DynamicJoinSchema.proto

package com.itspawan.protobuf;

public final class DynamicJoinSchema {
  private DynamicJoinSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DynamicSchemaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.itspawan.protobuf.DynamicSchema)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string rhsColumns = 1;</code>
     */
    java.util.List<java.lang.String>
        getRhsColumnsList();
    /**
     * <code>repeated string rhsColumns = 1;</code>
     */
    int getRhsColumnsCount();
    /**
     * <code>repeated string rhsColumns = 1;</code>
     */
    java.lang.String getRhsColumns(int index);
    /**
     * <code>repeated string rhsColumns = 1;</code>
     */
    com.google.protobuf.ByteString
        getRhsColumnsBytes(int index);

    /**
     * <code>repeated string lhsColumns = 2;</code>
     */
    java.util.List<java.lang.String>
        getLhsColumnsList();
    /**
     * <code>repeated string lhsColumns = 2;</code>
     */
    int getLhsColumnsCount();
    /**
     * <code>repeated string lhsColumns = 2;</code>
     */
    java.lang.String getLhsColumns(int index);
    /**
     * <code>repeated string lhsColumns = 2;</code>
     */
    com.google.protobuf.ByteString
        getLhsColumnsBytes(int index);

    /**
     * <code>repeated string selectableColumns = 3;</code>
     */
    java.util.List<java.lang.String>
        getSelectableColumnsList();
    /**
     * <code>repeated string selectableColumns = 3;</code>
     */
    int getSelectableColumnsCount();
    /**
     * <code>repeated string selectableColumns = 3;</code>
     */
    java.lang.String getSelectableColumns(int index);
    /**
     * <code>repeated string selectableColumns = 3;</code>
     */
    com.google.protobuf.ByteString
        getSelectableColumnsBytes(int index);

    /**
     * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
     */
    java.util.List<com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition> 
        getConditionsList();
    /**
     * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
     */
    com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition getConditions(int index);
    /**
     * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
     */
    int getConditionsCount();
    /**
     * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
     */
    java.util.List<? extends com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinConditionOrBuilder> 
        getConditionsOrBuilderList();
    /**
     * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
     */
    com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinConditionOrBuilder getConditionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.itspawan.protobuf.DynamicSchema}
   */
  public  static final class DynamicSchema extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.itspawan.protobuf.DynamicSchema)
      DynamicSchemaOrBuilder {
    // Use DynamicSchema.newBuilder() to construct.
    private DynamicSchema(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DynamicSchema() {
      rhsColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      lhsColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      selectableColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      conditions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DynamicSchema(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                rhsColumns_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              rhsColumns_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                lhsColumns_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              lhsColumns_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                selectableColumns_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              selectableColumns_.add(s);
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                conditions_ = new java.util.ArrayList<com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition>();
                mutable_bitField0_ |= 0x00000008;
              }
              conditions_.add(
                  input.readMessage(com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          rhsColumns_ = rhsColumns_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          lhsColumns_ = lhsColumns_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          selectableColumns_ = selectableColumns_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          conditions_ = java.util.Collections.unmodifiableList(conditions_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itspawan.protobuf.DynamicJoinSchema.internal_static_com_itspawan_protobuf_DynamicSchema_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itspawan.protobuf.DynamicJoinSchema.internal_static_com_itspawan_protobuf_DynamicSchema_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.class, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Builder.class);
    }

    /**
     * Protobuf enum {@code com.itspawan.protobuf.DynamicSchema.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>EQUAL = 0;</code>
       */
      EQUAL(0),
      /**
       * <code>NOT_EQUAL = 2;</code>
       */
      NOT_EQUAL(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>EQUAL = 0;</code>
       */
      public static final int EQUAL_VALUE = 0;
      /**
       * <code>NOT_EQUAL = 2;</code>
       */
      public static final int NOT_EQUAL_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Operation valueOf(int value) {
        return forNumber(value);
      }

      public static Operation forNumber(int value) {
        switch (value) {
          case 0: return EQUAL;
          case 2: return NOT_EQUAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Operation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.itspawan.protobuf.DynamicSchema.Operation)
    }

    public interface JoinConditionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.itspawan.protobuf.DynamicSchema.JoinCondition)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string lhsColumn = 1;</code>
       */
      java.lang.String getLhsColumn();
      /**
       * <code>optional string lhsColumn = 1;</code>
       */
      com.google.protobuf.ByteString
          getLhsColumnBytes();

      /**
       * <code>optional string rhsColumn = 2;</code>
       */
      java.lang.String getRhsColumn();
      /**
       * <code>optional string rhsColumn = 2;</code>
       */
      com.google.protobuf.ByteString
          getRhsColumnBytes();

      /**
       * <code>optional .com.itspawan.protobuf.DynamicSchema.Operation operation = 3;</code>
       */
      int getOperationValue();
      /**
       * <code>optional .com.itspawan.protobuf.DynamicSchema.Operation operation = 3;</code>
       */
      com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation getOperation();
    }
    /**
     * Protobuf type {@code com.itspawan.protobuf.DynamicSchema.JoinCondition}
     */
    public  static final class JoinCondition extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.itspawan.protobuf.DynamicSchema.JoinCondition)
        JoinConditionOrBuilder {
      // Use JoinCondition.newBuilder() to construct.
      private JoinCondition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private JoinCondition() {
        lhsColumn_ = "";
        rhsColumn_ = "";
        operation_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private JoinCondition(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                lhsColumn_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                rhsColumn_ = s;
                break;
              }
              case 24: {
                int rawValue = input.readEnum();

                operation_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.itspawan.protobuf.DynamicJoinSchema.internal_static_com_itspawan_protobuf_DynamicSchema_JoinCondition_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.itspawan.protobuf.DynamicJoinSchema.internal_static_com_itspawan_protobuf_DynamicSchema_JoinCondition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.class, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder.class);
      }

      public static final int LHSCOLUMN_FIELD_NUMBER = 1;
      private volatile java.lang.Object lhsColumn_;
      /**
       * <code>optional string lhsColumn = 1;</code>
       */
      public java.lang.String getLhsColumn() {
        java.lang.Object ref = lhsColumn_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lhsColumn_ = s;
          return s;
        }
      }
      /**
       * <code>optional string lhsColumn = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLhsColumnBytes() {
        java.lang.Object ref = lhsColumn_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lhsColumn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int RHSCOLUMN_FIELD_NUMBER = 2;
      private volatile java.lang.Object rhsColumn_;
      /**
       * <code>optional string rhsColumn = 2;</code>
       */
      public java.lang.String getRhsColumn() {
        java.lang.Object ref = rhsColumn_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rhsColumn_ = s;
          return s;
        }
      }
      /**
       * <code>optional string rhsColumn = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRhsColumnBytes() {
        java.lang.Object ref = rhsColumn_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rhsColumn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int OPERATION_FIELD_NUMBER = 3;
      private int operation_;
      /**
       * <code>optional .com.itspawan.protobuf.DynamicSchema.Operation operation = 3;</code>
       */
      public int getOperationValue() {
        return operation_;
      }
      /**
       * <code>optional .com.itspawan.protobuf.DynamicSchema.Operation operation = 3;</code>
       */
      public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation getOperation() {
        com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation result = com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation.valueOf(operation_);
        return result == null ? com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getLhsColumnBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lhsColumn_);
        }
        if (!getRhsColumnBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rhsColumn_);
        }
        if (operation_ != com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation.EQUAL.getNumber()) {
          output.writeEnum(3, operation_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getLhsColumnBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lhsColumn_);
        }
        if (!getRhsColumnBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rhsColumn_);
        }
        if (operation_ != com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation.EQUAL.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, operation_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition)) {
          return super.equals(obj);
        }
        com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition other = (com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition) obj;

        boolean result = true;
        result = result && getLhsColumn()
            .equals(other.getLhsColumn());
        result = result && getRhsColumn()
            .equals(other.getRhsColumn());
        result = result && operation_ == other.operation_;
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + LHSCOLUMN_FIELD_NUMBER;
        hash = (53 * hash) + getLhsColumn().hashCode();
        hash = (37 * hash) + RHSCOLUMN_FIELD_NUMBER;
        hash = (53 * hash) + getRhsColumn().hashCode();
        hash = (37 * hash) + OPERATION_FIELD_NUMBER;
        hash = (53 * hash) + operation_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.itspawan.protobuf.DynamicSchema.JoinCondition}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.itspawan.protobuf.DynamicSchema.JoinCondition)
          com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinConditionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.itspawan.protobuf.DynamicJoinSchema.internal_static_com_itspawan_protobuf_DynamicSchema_JoinCondition_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.itspawan.protobuf.DynamicJoinSchema.internal_static_com_itspawan_protobuf_DynamicSchema_JoinCondition_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.class, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder.class);
        }

        // Construct using com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          lhsColumn_ = "";

          rhsColumn_ = "";

          operation_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.itspawan.protobuf.DynamicJoinSchema.internal_static_com_itspawan_protobuf_DynamicSchema_JoinCondition_descriptor;
        }

        public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition getDefaultInstanceForType() {
          return com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.getDefaultInstance();
        }

        public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition build() {
          com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition buildPartial() {
          com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition result = new com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition(this);
          result.lhsColumn_ = lhsColumn_;
          result.rhsColumn_ = rhsColumn_;
          result.operation_ = operation_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition) {
            return mergeFrom((com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition other) {
          if (other == com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.getDefaultInstance()) return this;
          if (!other.getLhsColumn().isEmpty()) {
            lhsColumn_ = other.lhsColumn_;
            onChanged();
          }
          if (!other.getRhsColumn().isEmpty()) {
            rhsColumn_ = other.rhsColumn_;
            onChanged();
          }
          if (other.operation_ != 0) {
            setOperationValue(other.getOperationValue());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object lhsColumn_ = "";
        /**
         * <code>optional string lhsColumn = 1;</code>
         */
        public java.lang.String getLhsColumn() {
          java.lang.Object ref = lhsColumn_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            lhsColumn_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string lhsColumn = 1;</code>
         */
        public com.google.protobuf.ByteString
            getLhsColumnBytes() {
          java.lang.Object ref = lhsColumn_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            lhsColumn_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string lhsColumn = 1;</code>
         */
        public Builder setLhsColumn(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          lhsColumn_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string lhsColumn = 1;</code>
         */
        public Builder clearLhsColumn() {
          
          lhsColumn_ = getDefaultInstance().getLhsColumn();
          onChanged();
          return this;
        }
        /**
         * <code>optional string lhsColumn = 1;</code>
         */
        public Builder setLhsColumnBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          lhsColumn_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object rhsColumn_ = "";
        /**
         * <code>optional string rhsColumn = 2;</code>
         */
        public java.lang.String getRhsColumn() {
          java.lang.Object ref = rhsColumn_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            rhsColumn_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string rhsColumn = 2;</code>
         */
        public com.google.protobuf.ByteString
            getRhsColumnBytes() {
          java.lang.Object ref = rhsColumn_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            rhsColumn_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string rhsColumn = 2;</code>
         */
        public Builder setRhsColumn(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          rhsColumn_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string rhsColumn = 2;</code>
         */
        public Builder clearRhsColumn() {
          
          rhsColumn_ = getDefaultInstance().getRhsColumn();
          onChanged();
          return this;
        }
        /**
         * <code>optional string rhsColumn = 2;</code>
         */
        public Builder setRhsColumnBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          rhsColumn_ = value;
          onChanged();
          return this;
        }

        private int operation_ = 0;
        /**
         * <code>optional .com.itspawan.protobuf.DynamicSchema.Operation operation = 3;</code>
         */
        public int getOperationValue() {
          return operation_;
        }
        /**
         * <code>optional .com.itspawan.protobuf.DynamicSchema.Operation operation = 3;</code>
         */
        public Builder setOperationValue(int value) {
          operation_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .com.itspawan.protobuf.DynamicSchema.Operation operation = 3;</code>
         */
        public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation getOperation() {
          com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation result = com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation.valueOf(operation_);
          return result == null ? com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation.UNRECOGNIZED : result;
        }
        /**
         * <code>optional .com.itspawan.protobuf.DynamicSchema.Operation operation = 3;</code>
         */
        public Builder setOperation(com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Operation value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          operation_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .com.itspawan.protobuf.DynamicSchema.Operation operation = 3;</code>
         */
        public Builder clearOperation() {
          
          operation_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.itspawan.protobuf.DynamicSchema.JoinCondition)
      }

      // @@protoc_insertion_point(class_scope:com.itspawan.protobuf.DynamicSchema.JoinCondition)
      private static final com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition();
      }

      public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<JoinCondition>
          PARSER = new com.google.protobuf.AbstractParser<JoinCondition>() {
        public JoinCondition parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new JoinCondition(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<JoinCondition> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<JoinCondition> getParserForType() {
        return PARSER;
      }

      public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int RHSCOLUMNS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList rhsColumns_;
    /**
     * <code>repeated string rhsColumns = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRhsColumnsList() {
      return rhsColumns_;
    }
    /**
     * <code>repeated string rhsColumns = 1;</code>
     */
    public int getRhsColumnsCount() {
      return rhsColumns_.size();
    }
    /**
     * <code>repeated string rhsColumns = 1;</code>
     */
    public java.lang.String getRhsColumns(int index) {
      return rhsColumns_.get(index);
    }
    /**
     * <code>repeated string rhsColumns = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRhsColumnsBytes(int index) {
      return rhsColumns_.getByteString(index);
    }

    public static final int LHSCOLUMNS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList lhsColumns_;
    /**
     * <code>repeated string lhsColumns = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getLhsColumnsList() {
      return lhsColumns_;
    }
    /**
     * <code>repeated string lhsColumns = 2;</code>
     */
    public int getLhsColumnsCount() {
      return lhsColumns_.size();
    }
    /**
     * <code>repeated string lhsColumns = 2;</code>
     */
    public java.lang.String getLhsColumns(int index) {
      return lhsColumns_.get(index);
    }
    /**
     * <code>repeated string lhsColumns = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLhsColumnsBytes(int index) {
      return lhsColumns_.getByteString(index);
    }

    public static final int SELECTABLECOLUMNS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList selectableColumns_;
    /**
     * <code>repeated string selectableColumns = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSelectableColumnsList() {
      return selectableColumns_;
    }
    /**
     * <code>repeated string selectableColumns = 3;</code>
     */
    public int getSelectableColumnsCount() {
      return selectableColumns_.size();
    }
    /**
     * <code>repeated string selectableColumns = 3;</code>
     */
    public java.lang.String getSelectableColumns(int index) {
      return selectableColumns_.get(index);
    }
    /**
     * <code>repeated string selectableColumns = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSelectableColumnsBytes(int index) {
      return selectableColumns_.getByteString(index);
    }

    public static final int CONDITIONS_FIELD_NUMBER = 4;
    private java.util.List<com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition> conditions_;
    /**
     * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
     */
    public java.util.List<com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition> getConditionsList() {
      return conditions_;
    }
    /**
     * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
     */
    public java.util.List<? extends com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinConditionOrBuilder> 
        getConditionsOrBuilderList() {
      return conditions_;
    }
    /**
     * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
     */
    public int getConditionsCount() {
      return conditions_.size();
    }
    /**
     * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
     */
    public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition getConditions(int index) {
      return conditions_.get(index);
    }
    /**
     * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
     */
    public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinConditionOrBuilder getConditionsOrBuilder(
        int index) {
      return conditions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < rhsColumns_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rhsColumns_.getRaw(i));
      }
      for (int i = 0; i < lhsColumns_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lhsColumns_.getRaw(i));
      }
      for (int i = 0; i < selectableColumns_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, selectableColumns_.getRaw(i));
      }
      for (int i = 0; i < conditions_.size(); i++) {
        output.writeMessage(4, conditions_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < rhsColumns_.size(); i++) {
          dataSize += computeStringSizeNoTag(rhsColumns_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRhsColumnsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < lhsColumns_.size(); i++) {
          dataSize += computeStringSizeNoTag(lhsColumns_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getLhsColumnsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < selectableColumns_.size(); i++) {
          dataSize += computeStringSizeNoTag(selectableColumns_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSelectableColumnsList().size();
      }
      for (int i = 0; i < conditions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, conditions_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema)) {
        return super.equals(obj);
      }
      com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema other = (com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema) obj;

      boolean result = true;
      result = result && getRhsColumnsList()
          .equals(other.getRhsColumnsList());
      result = result && getLhsColumnsList()
          .equals(other.getLhsColumnsList());
      result = result && getSelectableColumnsList()
          .equals(other.getSelectableColumnsList());
      result = result && getConditionsList()
          .equals(other.getConditionsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getRhsColumnsCount() > 0) {
        hash = (37 * hash) + RHSCOLUMNS_FIELD_NUMBER;
        hash = (53 * hash) + getRhsColumnsList().hashCode();
      }
      if (getLhsColumnsCount() > 0) {
        hash = (37 * hash) + LHSCOLUMNS_FIELD_NUMBER;
        hash = (53 * hash) + getLhsColumnsList().hashCode();
      }
      if (getSelectableColumnsCount() > 0) {
        hash = (37 * hash) + SELECTABLECOLUMNS_FIELD_NUMBER;
        hash = (53 * hash) + getSelectableColumnsList().hashCode();
      }
      if (getConditionsCount() > 0) {
        hash = (37 * hash) + CONDITIONS_FIELD_NUMBER;
        hash = (53 * hash) + getConditionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.itspawan.protobuf.DynamicSchema}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.itspawan.protobuf.DynamicSchema)
        com.itspawan.protobuf.DynamicJoinSchema.DynamicSchemaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.itspawan.protobuf.DynamicJoinSchema.internal_static_com_itspawan_protobuf_DynamicSchema_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.itspawan.protobuf.DynamicJoinSchema.internal_static_com_itspawan_protobuf_DynamicSchema_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.class, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.Builder.class);
      }

      // Construct using com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConditionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        rhsColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        lhsColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        selectableColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (conditionsBuilder_ == null) {
          conditions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          conditionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.itspawan.protobuf.DynamicJoinSchema.internal_static_com_itspawan_protobuf_DynamicSchema_descriptor;
      }

      public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema getDefaultInstanceForType() {
        return com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.getDefaultInstance();
      }

      public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema build() {
        com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema buildPartial() {
        com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema result = new com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          rhsColumns_ = rhsColumns_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rhsColumns_ = rhsColumns_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          lhsColumns_ = lhsColumns_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.lhsColumns_ = lhsColumns_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          selectableColumns_ = selectableColumns_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.selectableColumns_ = selectableColumns_;
        if (conditionsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            conditions_ = java.util.Collections.unmodifiableList(conditions_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.conditions_ = conditions_;
        } else {
          result.conditions_ = conditionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema) {
          return mergeFrom((com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema other) {
        if (other == com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.getDefaultInstance()) return this;
        if (!other.rhsColumns_.isEmpty()) {
          if (rhsColumns_.isEmpty()) {
            rhsColumns_ = other.rhsColumns_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRhsColumnsIsMutable();
            rhsColumns_.addAll(other.rhsColumns_);
          }
          onChanged();
        }
        if (!other.lhsColumns_.isEmpty()) {
          if (lhsColumns_.isEmpty()) {
            lhsColumns_ = other.lhsColumns_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLhsColumnsIsMutable();
            lhsColumns_.addAll(other.lhsColumns_);
          }
          onChanged();
        }
        if (!other.selectableColumns_.isEmpty()) {
          if (selectableColumns_.isEmpty()) {
            selectableColumns_ = other.selectableColumns_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSelectableColumnsIsMutable();
            selectableColumns_.addAll(other.selectableColumns_);
          }
          onChanged();
        }
        if (conditionsBuilder_ == null) {
          if (!other.conditions_.isEmpty()) {
            if (conditions_.isEmpty()) {
              conditions_ = other.conditions_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureConditionsIsMutable();
              conditions_.addAll(other.conditions_);
            }
            onChanged();
          }
        } else {
          if (!other.conditions_.isEmpty()) {
            if (conditionsBuilder_.isEmpty()) {
              conditionsBuilder_.dispose();
              conditionsBuilder_ = null;
              conditions_ = other.conditions_;
              bitField0_ = (bitField0_ & ~0x00000008);
              conditionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getConditionsFieldBuilder() : null;
            } else {
              conditionsBuilder_.addAllMessages(other.conditions_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList rhsColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRhsColumnsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          rhsColumns_ = new com.google.protobuf.LazyStringArrayList(rhsColumns_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string rhsColumns = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRhsColumnsList() {
        return rhsColumns_.getUnmodifiableView();
      }
      /**
       * <code>repeated string rhsColumns = 1;</code>
       */
      public int getRhsColumnsCount() {
        return rhsColumns_.size();
      }
      /**
       * <code>repeated string rhsColumns = 1;</code>
       */
      public java.lang.String getRhsColumns(int index) {
        return rhsColumns_.get(index);
      }
      /**
       * <code>repeated string rhsColumns = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRhsColumnsBytes(int index) {
        return rhsColumns_.getByteString(index);
      }
      /**
       * <code>repeated string rhsColumns = 1;</code>
       */
      public Builder setRhsColumns(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRhsColumnsIsMutable();
        rhsColumns_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rhsColumns = 1;</code>
       */
      public Builder addRhsColumns(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRhsColumnsIsMutable();
        rhsColumns_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rhsColumns = 1;</code>
       */
      public Builder addAllRhsColumns(
          java.lang.Iterable<java.lang.String> values) {
        ensureRhsColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rhsColumns_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rhsColumns = 1;</code>
       */
      public Builder clearRhsColumns() {
        rhsColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rhsColumns = 1;</code>
       */
      public Builder addRhsColumnsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRhsColumnsIsMutable();
        rhsColumns_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList lhsColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLhsColumnsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          lhsColumns_ = new com.google.protobuf.LazyStringArrayList(lhsColumns_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string lhsColumns = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getLhsColumnsList() {
        return lhsColumns_.getUnmodifiableView();
      }
      /**
       * <code>repeated string lhsColumns = 2;</code>
       */
      public int getLhsColumnsCount() {
        return lhsColumns_.size();
      }
      /**
       * <code>repeated string lhsColumns = 2;</code>
       */
      public java.lang.String getLhsColumns(int index) {
        return lhsColumns_.get(index);
      }
      /**
       * <code>repeated string lhsColumns = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLhsColumnsBytes(int index) {
        return lhsColumns_.getByteString(index);
      }
      /**
       * <code>repeated string lhsColumns = 2;</code>
       */
      public Builder setLhsColumns(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLhsColumnsIsMutable();
        lhsColumns_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lhsColumns = 2;</code>
       */
      public Builder addLhsColumns(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLhsColumnsIsMutable();
        lhsColumns_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lhsColumns = 2;</code>
       */
      public Builder addAllLhsColumns(
          java.lang.Iterable<java.lang.String> values) {
        ensureLhsColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lhsColumns_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lhsColumns = 2;</code>
       */
      public Builder clearLhsColumns() {
        lhsColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lhsColumns = 2;</code>
       */
      public Builder addLhsColumnsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureLhsColumnsIsMutable();
        lhsColumns_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList selectableColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSelectableColumnsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          selectableColumns_ = new com.google.protobuf.LazyStringArrayList(selectableColumns_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string selectableColumns = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSelectableColumnsList() {
        return selectableColumns_.getUnmodifiableView();
      }
      /**
       * <code>repeated string selectableColumns = 3;</code>
       */
      public int getSelectableColumnsCount() {
        return selectableColumns_.size();
      }
      /**
       * <code>repeated string selectableColumns = 3;</code>
       */
      public java.lang.String getSelectableColumns(int index) {
        return selectableColumns_.get(index);
      }
      /**
       * <code>repeated string selectableColumns = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSelectableColumnsBytes(int index) {
        return selectableColumns_.getByteString(index);
      }
      /**
       * <code>repeated string selectableColumns = 3;</code>
       */
      public Builder setSelectableColumns(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSelectableColumnsIsMutable();
        selectableColumns_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string selectableColumns = 3;</code>
       */
      public Builder addSelectableColumns(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSelectableColumnsIsMutable();
        selectableColumns_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string selectableColumns = 3;</code>
       */
      public Builder addAllSelectableColumns(
          java.lang.Iterable<java.lang.String> values) {
        ensureSelectableColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, selectableColumns_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string selectableColumns = 3;</code>
       */
      public Builder clearSelectableColumns() {
        selectableColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string selectableColumns = 3;</code>
       */
      public Builder addSelectableColumnsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSelectableColumnsIsMutable();
        selectableColumns_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition> conditions_ =
        java.util.Collections.emptyList();
      private void ensureConditionsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          conditions_ = new java.util.ArrayList<com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition>(conditions_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinConditionOrBuilder> conditionsBuilder_;

      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public java.util.List<com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition> getConditionsList() {
        if (conditionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(conditions_);
        } else {
          return conditionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public int getConditionsCount() {
        if (conditionsBuilder_ == null) {
          return conditions_.size();
        } else {
          return conditionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition getConditions(int index) {
        if (conditionsBuilder_ == null) {
          return conditions_.get(index);
        } else {
          return conditionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public Builder setConditions(
          int index, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionsIsMutable();
          conditions_.set(index, value);
          onChanged();
        } else {
          conditionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public Builder setConditions(
          int index, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.set(index, builderForValue.build());
          onChanged();
        } else {
          conditionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public Builder addConditions(com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionsIsMutable();
          conditions_.add(value);
          onChanged();
        } else {
          conditionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public Builder addConditions(
          int index, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionsIsMutable();
          conditions_.add(index, value);
          onChanged();
        } else {
          conditionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public Builder addConditions(
          com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.add(builderForValue.build());
          onChanged();
        } else {
          conditionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public Builder addConditions(
          int index, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.add(index, builderForValue.build());
          onChanged();
        } else {
          conditionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public Builder addAllConditions(
          java.lang.Iterable<? extends com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition> values) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, conditions_);
          onChanged();
        } else {
          conditionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public Builder clearConditions() {
        if (conditionsBuilder_ == null) {
          conditions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          conditionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public Builder removeConditions(int index) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.remove(index);
          onChanged();
        } else {
          conditionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder getConditionsBuilder(
          int index) {
        return getConditionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinConditionOrBuilder getConditionsOrBuilder(
          int index) {
        if (conditionsBuilder_ == null) {
          return conditions_.get(index);  } else {
          return conditionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public java.util.List<? extends com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinConditionOrBuilder> 
           getConditionsOrBuilderList() {
        if (conditionsBuilder_ != null) {
          return conditionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(conditions_);
        }
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder addConditionsBuilder() {
        return getConditionsFieldBuilder().addBuilder(
            com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.getDefaultInstance());
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder addConditionsBuilder(
          int index) {
        return getConditionsFieldBuilder().addBuilder(
            index, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.getDefaultInstance());
      }
      /**
       * <code>repeated .com.itspawan.protobuf.DynamicSchema.JoinCondition conditions = 4;</code>
       */
      public java.util.List<com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder> 
           getConditionsBuilderList() {
        return getConditionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinConditionOrBuilder> 
          getConditionsFieldBuilder() {
        if (conditionsBuilder_ == null) {
          conditionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinCondition.Builder, com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema.JoinConditionOrBuilder>(
                  conditions_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          conditions_ = null;
        }
        return conditionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.itspawan.protobuf.DynamicSchema)
    }

    // @@protoc_insertion_point(class_scope:com.itspawan.protobuf.DynamicSchema)
    private static final com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema();
    }

    public static com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DynamicSchema>
        PARSER = new com.google.protobuf.AbstractParser<DynamicSchema>() {
      public DynamicSchema parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DynamicSchema(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DynamicSchema> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DynamicSchema> getParserForType() {
      return PARSER;
    }

    public com.itspawan.protobuf.DynamicJoinSchema.DynamicSchema getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_itspawan_protobuf_DynamicSchema_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_itspawan_protobuf_DynamicSchema_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_itspawan_protobuf_DynamicSchema_JoinCondition_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_itspawan_protobuf_DynamicSchema_JoinCondition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027DynamicJoinSchema.proto\022\025com.itspawan." +
      "protobuf\"\273\002\n\rDynamicSchema\022\022\n\nrhsColumns" +
      "\030\001 \003(\t\022\022\n\nlhsColumns\030\002 \003(\t\022\031\n\021selectable" +
      "Columns\030\003 \003(\t\022F\n\nconditions\030\004 \003(\01322.com." +
      "itspawan.protobuf.DynamicSchema.JoinCond" +
      "ition\032x\n\rJoinCondition\022\021\n\tlhsColumn\030\001 \001(" +
      "\t\022\021\n\trhsColumn\030\002 \001(\t\022A\n\toperation\030\003 \001(\0162" +
      "..com.itspawan.protobuf.DynamicSchema.Op" +
      "eration\"%\n\tOperation\022\t\n\005EQUAL\020\000\022\r\n\tNOT_E" +
      "QUAL\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_itspawan_protobuf_DynamicSchema_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_itspawan_protobuf_DynamicSchema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_itspawan_protobuf_DynamicSchema_descriptor,
        new java.lang.String[] { "RhsColumns", "LhsColumns", "SelectableColumns", "Conditions", });
    internal_static_com_itspawan_protobuf_DynamicSchema_JoinCondition_descriptor =
      internal_static_com_itspawan_protobuf_DynamicSchema_descriptor.getNestedTypes().get(0);
    internal_static_com_itspawan_protobuf_DynamicSchema_JoinCondition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_itspawan_protobuf_DynamicSchema_JoinCondition_descriptor,
        new java.lang.String[] { "LhsColumn", "RhsColumn", "Operation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
